config/routes.rb
Rails.application.routes.draw do

  resources :lists do
    resources :subscribers
  end

  resources :campaigns
  resources :templates

  root 'lists#index'

end

app/models/list.rb
class List < ActiveType::Object

  # this is not backed by a db table

  attribute :id, :integer
  attribute :name, :string
  attribute :company, :string
  attribute :address1, :string
  attribute :city, :string
  attribute :state, :string
  attribute :zip, :integer
  attribute :country, :string
  attribute :permission_reminder, :string
  attribute :from_name, :string
  attribute :from_email, :string
  attribute :subject, :string
  attribute :language, :string

  validates :name, presence: true
  validates :company, presence: true
  validates :address1, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true, numericality: true
  validates :country, presence: true
  validates :permission_reminder, presence: true
  validates :from_name, presence: true
  validates :from_email, presence: true, email: true
  validates :subject, presence: true
  validates :language, presence: true

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = @gibbon.lists.retrieve["lists"]
  end

  def show 
    @members = @gibbon.lists.send(params[:id]).members.retrieve["members"]
  end

  def new 
    @list = List.new
  end

  def create
    save_list or render 'new'
  end

  def destroy
    begin
      @gibbon.lists(params[:id]).delete
      flash[:success] = "List deleted."
    rescue Gibbon::MailChimpError => error
      flash[:error] = error
      false
    end

    redirect_to root_path
  end

  private

  def save_list 
    @list = List.new(params_list)

    # Call to save only validates
    if @list.save
      if gibbon_create_list
        redirect_to root_path
      end
    end
  end

  def gibbon_create_list
    body = {
      name: @list.name,
      contact: {
        company: @list.company,
        address1: @list.address1,
        city: @list.city,
        state: @list.city,
        zip: @list.zip.to_s,
        country: @list.country,
      },
      permission_reminder: @list.permission_reminder,
      campaign_defaults: {
        from_name: @list.from_name,
        from_email: @list.from_email,
        subject: @list.subject,
        language: @list.language 
      },
      email_type_option: true,
      visibility: "pub"
    }

    begin
      @gibbon.lists.create(body: body)
      flash[:success] = "List created."
    rescue Gibbon::MailChimpError => error
      @list.errors[:base] << error
      false
    end
  end

  def params_list
    params.require(:list).permit(:name, :company, :address1, :city, :state, :zip, :country, :permission_reminder, :from_name, :from_email, :subject, :language)
  end

end

app/helpers/lists_helper.rb
module ListsHelper
  def current_list
    @list_id = params[:list_id] || params[:id]
    @list = @list_id ? @gibbon.lists.send(@list_id).retrieve : {}
  end

  def lists
    @gibbon.lists.retrieve["lists"]
  end
end

app/views/lists/_list.html.erb
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <th>ID</th>
      <th>Name</th>
      <th>Company</th>
      <th>Permission Reminder</th>
      <th>From Email</th>
      <th>Date Created</th>
    </thead>
    <tbody>
      <tr>
        <% @list = current_list %>
        <td><%= @list["id"] %></td>
        <td><%= @list["name"] %></td>
        <td><%= @list["contact"]["company"] %></td>
        <td><%= @list["permission_reminder"] %></td>
        <td><%= @list["campaign_defaults"]["from_email"] %></td>
        <td><%= @list["date_created"] %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/lists/index.html.erb
<div class="container">
  <h2>
    <span>Lists</span>
    <%= link_to "Add List", new_list_path, class: 'btn btn-primary pull-right' %>
  </h2>
  <hr/>
</div>

<div class="table-responsive">
<table class="table table-striped">
  <thead>
    <th>ID</th>
    <th>Name</th>
    <th>Company</th>
    <th>Permission Reminder</th>
    <th>From Email</th>
    <th>Date Created</th>
    <th colspan="2">Options</th>
  </thead>
  <tbody>

    <% @lists.each do |list| %>
      <tr>
        <td><%= list["id"] %></td>
        <td><%= list["name"] %></td>
        <td><%= list["contact"]["company"] %></td>
        <td><%= list["permission_reminder"] %></td>
        <td><%= list["campaign_defaults"]["from_email"] %></td>
        <td><%= list["date_created"] %></td>
        <td>
          <%= link_to "View", list_path(list["id"]), class: 'btn btn-info' %>
        </td>
        <td>
          <%= link_to "Delete", list_path(list["id"]), method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure?" } %>
        </td>
      </tr>
    <% end %>

  </tbody>
</table>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h2>
    <span>Input New list</span>
    <%= link_to "Cancel", root_path, class: 'btn btn-warning pull-right' %>
  </h2>
  <hr/>
</div>

<%= form_for @list, url: lists_path, method: :post do |f| %>

  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h4>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
    
  <div class="form-group">
    <%= f.label :company %>
    <%= f.text_field :company %>
  </div>
    
  <div class="form-group">
    <%= f.label :address1, "Address" %>
    <%= f.text_field :address1 %>
  </div>
    
  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
    
  <div class="form-group">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>
    
  <div class="form-group">
    <%= f.label :zip %>
    <%= f.text_field :zip %>
  </div>
    
  <div class="form-group">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>
    
  <div class="form-group">
    <%= f.label :permission_reminder %>
    <%= f.text_field :permission_reminder %>
  </div>
    
  <div class="form-group">
    <%= f.label :from_name %>
    <%= f.text_field :from_name %>
  </div>
    
  <div class="form-group">
    <%= f.label :from_email %>
    <%= f.text_field :from_email %>
  </div>
    
  <div class="form-group">
    <%= f.label :subject %>
    <%= f.text_field :subject %>
  </div>
    
  <div class="form-group">
    <%= f.label :language %>
    <%= f.text_field :language %>
  </div>
    
  <%= f.submit class: "btn btn-primary" %>

<% end %>

app/views/lists/show.html.erb
<%= render 'list' %>

<div class="container">
  <h2>
    <span>Subscribers</span>
    <%= link_to "Add Subscriber", new_list_subscriber_path(list_id: @list_id), class: 'btn btn-primary pull-right' %>
  </h2>
  <hr/>
</div>

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <th>ID</th>
      <th>Name</th>
      <th>Email</th>
      <th>Status</th>
      <th>Avg Open Rate</th>
    </thead>
    <tbody>
      <% @members.each do |member| %>
        <tr>
          <td><%= member["id"] %></td>
          <td><%= member["merge_fields"]["FNAME"] %> <%= member["merge_fields"]["LNAME"] %></td>
          <td><%= member["email_address"] %></td>
          <td><%= member["status"] %></td>
          <td><%= member["stats"]["avg_open_rate"] %></td>
          <td><%= link_to "Unsubscribe", list_subscriber_path(list_id: @list_id, id: member["id"]), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?" } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>