config/routes.rb
Rails.application.routes.draw do

  resources :lists do
    resources :subscribers
  end

  resources :campaigns
  resources :templates

  root 'lists#index'

end

app/models/campaign.rb
class Campaign < ActiveType::Object

  # this is not backed by a db table

  attribute :id, :string
  attribute :template_id, :integer
  attribute :list_id, :string
  attribute :subject_line, :string
  attribute :title, :string
  attribute :from_name, :string
  attribute :reply_to, :string

  validates :template_id, presence: true
  validates :list_id, presence: true
  validates :subject_line, presence: true
  validates :title, presence: true
  validates :from_name, presence: true
  validates :reply_to, presence: true, email: true

end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :load_mailchimp_campaign, only: [:edit, :update]
  before_action :set_template, only: [:new, :create]

  def index
    @campaigns = @gibbon.campaigns.retrieve(params: {count: "30"})["campaigns"]
  end

  def show 
    begin
      @gibbon.campaigns.send(params[:id]).actions.send.create
      flash[:success] = "Campaign sent."
    rescue Gibbon::MailChimpError => error
      flash[:error] = error
      false
    end

    redirect_to campaigns_path
  end

  def new 
    @campaign = Campaign.new
    @campaign.template_id = @template["id"]
  end

  def create
    save_campaign or render 'new'
  end

  def edit
  end

  def update
    update_campaign or render 'edit'
  end

  def destroy
    begin
      @gibbon.campaigns(params[:id]).delete
      flash[:success] = "Campaign deleted."
    rescue Gibbon::MailChimpError => error
      flash[:error] = error
      false
    end

    redirect_to campaigns_path
  end

  private

  def load_mailchimp_campaign
    mc = @gibbon.campaigns(params[:id]).retrieve
    @campaign = Campaign.create({
      template_id:  mc["settings"]["template_id"],
      list_id:      mc["recipients"]["list_id"],
      subject_line: mc["settings"]["subject_line"],
      title:        mc["settings"]["title"],
      from_name:    mc["settings"]["from_name"],
      reply_to:     mc["settings"]["reply_to"]
    })
    @campaign.id = params[:id] # Presense of ID field triggers update
    set_template @campaign.template_id
  end

  def save_campaign 
    @campaign = Campaign.new(params_campaign)
    @campaign.template_id = @template["id"]

    if @campaign.valid?
      if gibbon_save_campaign
        redirect_to campaigns_path
      end
    end
  end

  def update_campaign 
    p = params_campaign

    @campaign.template_id  = p[:template_id]
    @campaign.list_id      = p[:list_id]
    @campaign.subject_line = p[:subject_line]
    @campaign.title        = p[:title]
    @campaign.from_name    = p[:from_name]
    @campaign.reply_to     = p[:reply_to]

    if @campaign.valid?
      if gibbon_update_campaign
        redirect_to campaigns_path
      end
    end
  end

  def gibbon_save_campaign
    recipients = { list_id: @campaign.list_id }
    settings = { 
      :subject_line => @campaign.subject_line, 
      :title => @campaign.title,
      :from_name => @campaign.from_name,
      :reply_to => @campaign.reply_to
    }
    body = { 
      type: "regular", 
      recipients: recipients, 
      settings: settings
    }
    update_body = { 
      template: { id: @campaign.template_id } 
    }

    begin
      campaign = @gibbon.campaigns.create(body: body)

      @gibbon.campaigns(campaign["id"]).content.upsert(body: update_body)
      flash[:success] = "Campaign created."
      true

    rescue Gibbon::MailChimpError => error
      # puts "Gibbon::MailChimpError: #{e.message} - #{e.raw_body}"
      @campaign.errors[:base] << error
      false
    end
  end

  def gibbon_update_campaign
    recipients = { list_id: @campaign.list_id }
    settings = { 
      :subject_line => @campaign.subject_line, 
      :title => @campaign.title,
      :from_name => @campaign.from_name,
      :reply_to => @campaign.reply_to
    }
    body = { 
      type: "regular", 
      recipients: recipients, 
      settings: settings, 
      template: { id: @campaign.template_id } 
    }

    begin

      # @gibbon.campaigns(params[:id]).content.upsert(body: body)
      # @gibbon.campaigns(params[:id]).update(body: body)

      @gibbon.campaigns.send(params[:id]).update(body: body)

      flash[:success] = "Campaign updated."
      true

    rescue Gibbon::MailChimpError => error
      @campaign.errors[:base] << error
      false
    end
  end

  def set_template(id = nil)
    template_id = get_template_id

    if template_id.blank?
      template_id = id
    end

    if template_id == 0 || template_id.blank?
      flash[:info] = "Select template to use on campaign."
      redirect_to templates_path(campaign_id: params[:id])

    else
      begin
        @template = @gibbon.templates(template_id).retrieve

      rescue Gibbon::MailChimpError => error
        flash[:danger] = "Template ID: %s cannot be used." % template_id
        flash[:error] = error
        redirect_to templates_path
      end
    end
  end

  def get_template_id
    params[:template_id] || (params[:campaign][:template_id] if params[:campaign])
  end

  def params_campaign
    params.require(:campaign).permit(:template_id, :list_id, :subject_line, :title, :from_name, :reply_to)
  end

end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_form.html.erb
<%= form_for(@campaign) do |f| %>

  <% if @campaign.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@campaign.errors.count, "error") %> prohibited this campaign from being saved:</h4>
      <ul>
        <% @campaign.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :template_id %>

  <div class="form-group">
    <%= f.label :list_id %>
    <%= f.select(:list_id, lists.map { |f| [f["name"], f["id"]] }, :prompt => "Select target list") %>
  </div>

  <div class="form-group">
    <%= f.label :subject_line %>
    <%= f.text_field :subject_line %>
  </div>
    
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
    
  <div class="form-group">
    <%= f.label :from_name %>
    <%= f.text_field :from_name %>
  </div>
    
  <div class="form-group">
    <%= f.label :reply_to %>
    <%= f.text_field :reply_to, :placeholder => 'Email address' %>
  </div>
    
  <%= f.submit class: "btn btn-primary" %>

<% end %>

app/views/campaigns/edit.html.erb
<div class="container">
  <h2>
    <span>Edit campaign</span>
    <%= link_to "Cancel", campaigns_path, class: 'btn btn-warning pull-right' %>
  </h2>
  <hr/>
</div>

<div class="row">
  <div class="col-md-6">
    <%= image_tag @template["thumbnail"], class: 'template-thumbnail-x2' %>
  </div>

  <div class="col-md-6">
    <%= render 'form' %>
  </div>
</div>

app/views/campaigns/index.html.erb
<div class="container">
  <h2>
    <span>Campaigns</span>
    <%= link_to "Add Campaign", new_campaign_path, class: 'btn btn-primary pull-right' %>
  </h2>
  <hr/>
</div>

<div class="table-responsive">
<table class="table table-striped">
  <thead>
    <th>ID</th>
    <th>Recipient List</th>
    <th>Status</th>
    <th>Sent</th>
    <th>Subject : Title</th>
    <th>Open Rate</th>
    <th>Created</th>
    <th colspan="3">Options</th>
  </thead>
  <tbody>

    <% @campaigns.each do |campaign| %>
      <tr>
        <td><%= link_to campaign["id"], campaign["archive_url"] %></td>
        <td><%= campaign["recipients"]["list_id"] %></td>
        <td><%= campaign["status"] %></td>
        <td><%= campaign["emails_sent"] %></td>
        <td><%= campaign["settings"]["subject_line"] + " : " + campaign["settings"]["title"] %></td>
        <td><%= campaign["send_time"].blank? ? 0 : campaign["report_summary"]["open_rate"].round(2) %></td>
        <td><%= campaign["create_time"] %></td>
        <td>
          <%= link_to "Edit", edit_campaign_path(campaign["id"]), class: 'btn btn-primary' %>
        </td>
        <td>
          <%= link_to "Delete", campaign_path(campaign["id"]), method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure?" } %>
        </td>
        <td>
          <% if campaign["status"] != "sent" %>
            <%= link_to "Send", campaign_path(campaign["id"]), class: 'btn btn-success' %>
          <% end %>
        </td>
      </tr>
    <% end %>

  </tbody>
</table>

</div>

app/views/campaigns/new.html.erb
<div class="container">
  <h2>
    <span>Input New campaign</span>
    <%= link_to "Cancel", campaigns_path, class: 'btn btn-warning pull-right' %>
  </h2>
  <hr/>
</div>

<div class="row">
  <div class="col-md-6">
    <%= image_tag @template["thumbnail"], class: 'template-thumbnail-x2' %>
  </div>

  <div class="col-md-6">
    <%= render 'form' %>
  </div>
</div>